apiVersion: v1
kind: Service
metadata:
  name: {{ include "venice.fullname" . }}-router
  labels:
    {{- include "venice.labels.router" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.venice.router.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.venice.router.service.type }}
  ports:
    {{ toYaml .Values.venice.router.service.ports | nindent 4 }}
  selector:
    {{- include "venice.selectorLabels.router" . | nindent 4 }}
