#
#  Copyright 2022 DataStax, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "venice.fullname" . }}-router
  namespace: {{ .Release.Namespace }}
data:
  VENICECONF_zookeeper_address: "{{ .Values.zookeeper.address }}"
  VENICECONF_kafka_bootstrap_servers: "{{ .Values.kafka.address }}"
  VENICECONF_r2d2Client_zkHosts: "{{ .Values.zookeeper.address }}"
  VENICECONF_kafka_zk_address: "NOT-USED"
  {{- if .Values.authentication.enableTokenAuth }}
  VENICECONF_authentication_service_class: "com.linkedin.venice.authentication.jwt.TokenAuthenticationService"
  VENICECONF_authorizer_service_class: "com.linkedin.venice.authorization.SimpleAuthorizerService"
  {{- if .Values.authentication.publicKeySecretName }}
  VENICECONF_authentication_jwt_publicKey: "file:///venice/jwtPublicKey/{{ .Values.authentication.tokenPublicKeyFile }}"
  {{- end }}
  
  {{- end }}
  {{- if .Values.venice.router.ssl.enabled }}
  VENICECONF_ssl_enabled: "true"
  VENICECONF_router_local_ssl: "false"
  # mTLS ACL is not supported
  VENICECONF_ssl_needs_client_cert: "false"
  {{- end }}
  {{- range $key, $val := $.Values.venice.router.configData }}
  {{ $key }}: {{ $val | replace "\"" "" | trim | quote }}
  {{- end }}