apiVersion: v1
kind: Service
metadata:
  name: {{ include "venice.fullname" . }}-router
  labels:
    {{- include "venice.labels.router" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7777
      name: http
    - port: 7778
      name: https
  selector:
    {{- include "venice.selectorLabels.router" . | nindent 4 }}
