apiVersion: v1
kind: Service
metadata:
  name: {{ include "venice.fullname" . }}-controller
  labels:
    {{- include "venice.labels.controller" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5555
      name: http
  selector:
    {{- include "venice.selectorLabels.controller" . | nindent 4 }}
