apiVersion: v1
kind: Service
metadata:
  name: {{ include "venice.fullname" . }}-controller
  labels:
    {{- include "venice.labels.controller" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.venice.controller.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.venice.controller.service.type }}
  ports:
    {{ toYaml .Values.venice.controller.service.ports | nindent 4 }}
  selector:
    {{- include "venice.selectorLabels.controller" . | nindent 4 }}
