# Default values for venice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  client:
    repository: eolivellidatastax/venice-client
    pullPolicy: IfNotPresent
    tag: 0.4.17-10
  server:
    repository: eolivellidatastax/venice-server
    pullPolicy: IfNotPresent
    tag: 0.4.17-10
  router: 
    repository: eolivellidatastax/venice-router
    pullPolicy: IfNotPresent
    tag: 0.4.17-10
  controller:
    repository: eolivellidatastax/venice-controller
    pullPolicy: IfNotPresent
    tag: 0.4.17-10

zookeeper:
  address: "pulsar-zookeeper-ca.mypulsar.svc.cluster.local:2181"

kafka:
  address: "pulsar-proxy.mypulsar.svc.cluster.local:9092"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe: false