apiVersion: v1
kind: Service
metadata:
  name: "{{ template "venice.fullname" . }}-server"
  labels:
    {{- include "venice.labels.server" . | nindent 4 }}
  annotations:
{{ toYaml .Values.venice.server.service.annotations | indent 4 }}
spec:
  ports:
{{ toYaml .Values.venice.server.service.ports | indent 2 }}
  clusterIP: None
  selector:
    {{- include "venice.selectorLabels.server" . | nindent 4 }}
