{{- if .Values.persistence }}
{{- if not .Values.default_storage.existingStorageClassName }}
{{- if not .Values.venice.volumes.rocksdb.existingStorageClassName }}
{{- if or .Values.venice.volumes.rocksdb.storageClass .Values.default_storage}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ template "venice.fullname" . }}-server"
  namespace: {{ .Release.Namespace }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- if .Values.venice.volumes.rocksdb.storageClass }}
reclaimPolicy: {{ .Values.venice.volumes.rocksdb.storageClass.reclaimPolicy | default .Values.default_storage.reclaimPolicy }}
provisioner: {{ .Values.venice.volumes.rocksdb.storageClass.provisioner }}
parameters:
  {{- if .Values.venice.volumes.rocksdb.storageClass.type }}
  type: {{ .Values.venice.volumes.rocksdb.storageClass.type }}
  {{- end }}
  {{- if .Values.venice.volumes.rocksdb.storageClass.fsType }}
  fsType: {{ .Values.venice.volumes.rocksdb.storageClass.fsType }}
  {{- end }}
  {{- if .Values.venice.volumes.rocksdb.storageClass.extraParams }}
{{ toYaml .Values.venice.volumes.rocksdb.storageClass.extraParams | indent 2 }}
  {{- end }}
{{- else if .Values.default_storage }}
reclaimPolicy: {{ .Values.default_storage.reclaimPolicy }}
provisioner: {{ .Values.default_storage.provisioner }}
parameters:
  {{- if .Values.default_storage.type }}
  type: {{ .Values.default_storage.type }}
  {{- end }}
  {{- if .Values.default_storage.fsType }}
  fsType: {{ .Values.default_storage.fsType }}
  {{- end }}
  {{- if .Values.default_storage.extraParams }}
{{ toYaml .Values.default_storage.extraParams | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
# End for if persistence for whole file
{{- end }}

